ls:
    .dir: camelCase | PascalCase
    .js: camelCase | PascalCase
    .json: camelCase
    .ts: camelCase | PascalCase
    .tsx: PascalCase
    .test.ts: camelCase | PascalCase
    .test.tsx: PascalCase
    .d.ts: kebab-case
    
ignore:
    - .eslintrc.js
    - .git
    - .github
    - .husky
    - .idea
    - .ls-lint.yml
    - .nyc_output
    - .vscode
    - babel.config.js
    - coverage
    - dist
    - docker
    - jest.config.js
    - node_modules
    - tsconfig.build.json
